services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=remitly_db
    ports:
      - "5432:5432"
    volumes:
      - remitly_db_vol:/var/lib/postgresql/data
    networks:
      - remitly-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/remitly_db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    depends_on:
      - postgres
    networks:
      - remitly-network

volumes:
  remitly_db_vol:

networks:
  remitly-network:
    driver: bridge
