services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=remitly_db
    ports:
      - "5432:5432"
    volumes:
      - remitly_db_vol:/var/lib/postgresql/data
    networks:
      - remitly-network

volumes:
  remitly_db_vol:

networks:
  remitly-network:
    driver: bridge
