spring:
  application:
    name: remitly-home-exercise
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
    flyway:
      enabled: true
      baseline-on-migrate: true
server:
  port: 8080
app:
  file-path: data.xlsx
