spring:
  application:
    name: remitly-home-exercise
  datasource:
    url: jdbc:postgresql://localhost:5432/remitly_db
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
    flyway:
      enabled: true
      baseline-on-migrate: true
server:
  port: 8080
app:
  file-path: data.xlsx
